### ISSUE TITLE
Training SentencePiece

### ISSUE THREAD

**Issue by pvcastro** [piegu/language-models#4]
Hi @piegu !

I would like to train a sentencepiece with a larger vocabulary. Would you mind sharing the step you followed to train your sentencepiece model? Including the pre-processing steps you did before.

Thanks!

**Comment by piegu** [comment]
Hi @pvcastro,

First of all, there is no pre-processing to do with SentencePiece. By default, SentencePiece uses its Unigram Language Model in order to find the segmentation method most suited to the training corpus.

Then, you ask about "train(ing) a sentencepiece with a larger vocabulary". You just have to pass your number (not 15k but 30k?, 60k? mais?). In fastai, you do it in the databunch through the [class SPProcessor](https://docs.fast.ai/text.data.html#SPProcessor) as following (code extracted from my notebook [lm3-portuguese.ipynb](https://github.com/piegu/language-models/blob/master/lm3-portuguese.ipynb)):

```
data = (TextList.from_folder(dest, processor=[OpenFileProcessor(), SPProcessor(max_vocab_sz=15000)])
        .split_by_rand_pct(0.1, seed=42)
        .label_for_lm()
        .databunch(bs=bs, num_workers=1))
```

At last, I publicated on medium a post about my understanding of SentencePiece: "[NLP & fastai | SentencePiece](https://medium.com/@pierre_guillou/nlp-fastai-sentencepiece-d6922b5480d6)". The post is in French but Google Translate is our friend :-) 

Hope that my answers help you. If not, please ask me again.

**Comment by pvcastro** [comment]
Hi @piegu, thanks for the reply!

I'm trying to replicate an ALBERT pretraining for portuguese, and for that I needed to train a sentencepiece for portuguese as well. The only one I found was yours, but your vocab of 15.000 was around half of what I've been seeing applied in transformers training. 

I was using this script as reference for training sentencepiece:

[https://github.com/yoheikikuta/bert-japanese/blob/master/src/train-sentencepiece.py](https://github.com/yoheikikuta/bert-japanese/blob/master/src/train-sentencepiece.py)

The wikipedia corpus in this repo (and in others I saw) is pre-processed prior to training sentencepiece, as shown [here](https://github.com/yoheikikuta/bert-japanese/blob/master/src/file-preprocessing.sh). I had a problem here because I had to add a pre-processing step to separate tokens from punctuation. Training sentencepiece without doing this led to some problems in tokenizing the corpus for ALBERT pretraining. Not sure why this happened. 

So the reason I asked you is because your sentencepiece model didn't seem to have this problem that mine had.

**Comment by piegu** [comment]
Hi @pvcastro,

I understand better what is your **pre-processing on a Wikipedia corpus** ([script](https://github.com/yoheikikuta/bert-japanese/blob/master/src/file-preprocessing.sh)). Its main objective is to remove `</doc>` and `<doc id=...>` but it has nothing to deal with SentencePiece. This is your decision to apply this kind of pre-processing before using a tokenizer (spaCy, SentencePiece, etc.).

One comment: I'm strongly against the action of this pre-processing script that "converts upper case characters to lower case ones.". It deletes a lot of semantic information doing that! "I like this car" and "I LIKE this car" are not exactly the same phrases.

In [fastai tokenization](https://docs.fast.ai/text.transform.html#Tokenization), there are special tokens to deal whith upper cases like **xxmaj** which is used to indicate that the next word begins with a capital in the original text and **xxup** which is used to indicate that the next word is written in all caps in the original text.

About "I had to add a pre-processing step to separate tokens from punctuation": from my point of view, you should not doing that, in particular because 1) by doing that, you create a corpus with different meanings that the original one (it could happen that the author of a Wikipedia article put spaces around punctuation on purpose) 2) you will not be able to detokenize and get back the original corpus. This is well explained here https://github.com/google/sentencepiece#whitespace-is-treated-as-a-basic-symbol

When using a Deep Learning model like a Language Model, the less pre-processing you apply, the best it is.

About using a vocab size for SentencePiece bigger than 15 000, I do not understand your problem. Just pass your number into the option `--vocab_size={vocab_size}, no?

**Comment by pvcastro** [comment]
Hi @piegu 

> One comment: I'm strongly against the action of this pre-processing script that "converts upper case characters to lower case ones.". It deletes a lot of semantic information doing that! "I like this car" and "I LIKE this car" are not exactly the same phrases.

I agree with you. I didn't use this part of the script, I just showed you the example I was using as a reference for my own script. 

> About using a vocab size for SentencePiece bigger than 15 000, I do not understand your problem. Just pass your number into the option `--vocab_size={vocab_size}, no?

Sure, my question for you wasn't because I wanted to know "how to increase the vocab size". I wanted to know your **whole solution**, the parameters you used for sentencepiece, etc.

> About "I had to add a pre-processing step to separate tokens from punctuation": from my point of view, you should not doing that

I also agree with you here, but I saw no other way to deal with this problem I had. Let me explain to you what happened:

I trained my own sentencepiece using the script I mentioned before. For a particular sentence from the wikipedia corpus, I had the following text:

> na superliga 2012/2013, foi vice-campeão

When I was running the [create_pretraining_data.py](https://github.com/google-research/google-research/blob/master/albert/create_pretraining_data.py) script from the albert repository using my trained sentencepiece model, the method [encode_pieces](https://github.com/google-research/google-research/blob/b13a2d98f590495331e27b86268b000413ecb50d/albert/tokenization.py#L106) calls the sentencepiece model to tokenize the sentence, but, for some reason, it doesn't split 2012/2013, into '2012', '/', '2013' and ','. In the line 119 from this method it verifies that the comma is the last character from the '2013,' token, and then it tries to convert the token into a binary format, which eventually leads to an error when this binary token is processed later in the script. 

I tested two other sentencepiece models, and both of them performed the split as expected, separating '2013' from ',', so this conversion to binary doesn't happen, and the script finishes as expected. The problem is that one of these models I tested was from english, and the other one was yours, with the 15.000 vocab. So this is when I asked you how you trained your own, to see if I could get a working sentencepiece model for portuguese that would perform that split as expected. 

Do you understand the context now?

Thanks!

**Comment by piegu** [comment]
I understand better but I can't help you. I guess there is a problem somewhere with scripts/corpus you use. On my side, I use SentencePiece within fastai v1. You can find the code [here](https://github.com/fastai/fastai/blob/master/fastai/text/data.py#L439). As an example, this is the code of the class SPProcessor that tokenizes and numericalizes with SentencePiece:

```
class SPProcessor(PreProcessor):
    "`PreProcessor` that tokenizes and numericalizes with `sentencepiece`"
    def __init__(self, ds:ItemList=None, pre_rules: ListRules=None, post_rules:ListRules=None, vocab_sz:int=None,
                 max_vocab_sz:int=30000, model_type:str='unigram', max_sentence_len:int=20480, lang='en',
                 char_coverage=None, tmp_dir='tmp', mark_fields:bool=False, include_bos:bool=True, 
                 include_eos:bool=False, sp_model=None, sp_vocab=None, n_cpus:int=None, enc='utf8'):
        try: from sentencepiece import SentencePieceTrainer,SentencePieceProcessor
        except ImportError:
            raise Exception('sentencepiece module is missing: run `pip install sentencepiece`')
        self.pre_rules,self.post_rules,self.enc = pre_rules,post_rules,enc
        self.mark_fields,self.include_bos,self.include_eos = mark_fields,include_bos,include_eos
        self.sp_model,self.sp_vocab,self.n_cpus = sp_model,sp_vocab,ifnone(n_cpus,defaults.cpus)
        self.train_func = partial(train_sentencepiece, pre_rules=pre_rules, post_rules=post_rules, vocab_sz=vocab_sz,
                max_vocab_sz=max_vocab_sz, model_type=model_type, max_sentence_len=max_sentence_len, lang=lang,
                char_coverage=char_coverage, tmp_dir=tmp_dir, enc=enc)
```

**Comment by pvcastro** [comment]
Great, thanks!
