### ISSUE TITLE
Fine-tuning of the LM and classifier do not use the SentencePiece in lm3-portuguese-classifier-olist.ipynb

### ISSUE THREAD

**Issue by rubensmau** [piegu/language-models#6]
You need to also update  lm3-portuguese-classifier-olist.ipynb , as you did in the Jurisprudencia notebook to use the SentencePiece model and vocab already trained.

Bom trabalho !!

**Comment by piegu** [comment]
Hi @rubensmau,

Thanks for your alert. You are right and you are welcome to do so and publish your results. On my side, I just published a warning in the [README.md](https://github.com/piegu/language-models/blob/master/README.md) file. 

For people they do not understand the point. We are talking about the notebook [lm3-portuguese-classifier-olist.ipynb](https://github.com/piegu/language-models/blob/master/lm3-portuguese-classifier-olist.ipynb).

- Instead of this actual code:

```
data_lm = (TextList.from_df(df_trn_val, path, cols=reviews, 
                            processor=[OpenFileProcessor(), SPProcessor(max_vocab_sz=15000)])
    .split_by_rand_pct(0.1, seed=42)
    .label_for_lm()           
    .databunch(bs=bs, num_workers=1))
```

You should use this following one in order to use the SentencePiece model and vocab already trained for the Portuguese Language Model in the notebook [lm3-portuguese.ipynb](https://github.com/piegu/language-models/blob/master/lm3-portuguese.ipynb):

```
data_lm = (TextList.from_df(df_trn_val, path, cols=reviews, processor=SPProcessor.load(dest))
    .split_by_rand_pct(0.1, seed=42)
    .label_for_lm()           
    .databunch(bs=bs, num_workers=1))
```
